# Generated by Django 4.0.1 on 2022-05-23 09:02

from django.db import migrations


def add_data(apps, schema_editor):
    User = apps.get_model("core", "User")
    db_alias = schema_editor.connection.alias
    Roles = apps.get_model("core", "Roles")
    Ord_User = Roles.objects.get(name=1)
    Company = Roles.objects.get(name=2)
    User.objects.using(db_alias).bulk_create([
        User(fullname="RunPython User", phone="998903231234", email="pythonUser@mail.ru", role=Ord_User),
        User(fullname="RunPython Company", phone="998903235431", email="pythonCompany@mail.ru", role=Company)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(add_data, None)
    ]
