
# Generated by Django 4.0.1 on 2022-05-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220523_1428'),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM User WHERE fullname='RunPython User'"
        ),
        migrations.RunSQL(
            "DELETE FROM User WHERE fullname='RunPython Company'"
        )
    ]
